import {
  modelCapabilitySchema,
  type ModelCapability,
} from "@/lib/generation/capability";

const verifiedAt = "2026-08-22";
const schemaVersion = "openapi-1.0.0";
const noEstimate = {
  estimateAvailable: false,
  text: "Exact credit use depends on the selected model and effective settings. Usage remains estimated until an authoritative completion record arrives.",
} as const;

const capabilities = [
  {
    contractVersion: "1.0.0",
    appModelKey: "seedance-2",
    version: 1,
    displayName: "Seedance 2",
    modelMaker: "ByteDance",
    mediaKind: "video",
    adapter: "seedance2",
    providerModelId: "bytedance/seedance-2",
    supportedModes: [
      "text-to-video",
      "first-frame-to-video",
      "first-and-last-frame-to-video",
      "multimodal-reference-to-video",
    ],
    prompt: { minimum: 3, maximum: 20000 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["480p", "720p", "1080p", "4k"],
        required: false,
        defaultValue: { value: "720p", source: "provider" },
        help: "480p, 720p, 1080p, or 4k.",
      },
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: ["1:1", "4:3", "3:4", "16:9", "9:16", "21:9", "adaptive"],
        required: true,
        defaultValue: { value: "16:9", source: "provider" },
        help: "Documented output aspect ratios, including adaptive.",
      },
      {
        key: "duration",
        label: "Duration",
        providerField: "duration",
        kind: "integer",
        minimum: 4,
        maximum: 15,
        step: 1,
        required: false,
        defaultValue: { value: 5, source: "provider" },
        help: "Whole seconds from 4 through 15.",
      },
      {
        key: "audio",
        label: "Generate audio",
        providerField: "generate_audio",
        kind: "boolean",
        required: false,
        defaultValue: { value: true, source: "provider" },
        help: "Generate synchronized audio with the output.",
      },
      {
        key: "webSearch",
        label: "Web search",
        providerField: "web_search",
        kind: "boolean",
        required: false,
        help: "Allow the model to use online search.",
      },
    ],
    references: [
      {
        role: "first_frame",
        label: "First frame",
        providerField: "first_frame_url",
        inputKind: "image",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: [
          "image/jpeg",
          "image/png",
          "image/webp",
          "image/bmp",
          "image/tiff",
          "image/gif",
        ],
        maxBytes: 30000000,
        requiresGroup: false,
      },
      {
        role: "last_frame",
        label: "Last frame",
        providerField: "last_frame_url",
        inputKind: "image",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: [
          "image/jpeg",
          "image/png",
          "image/webp",
          "image/bmp",
          "image/tiff",
          "image/gif",
        ],
        maxBytes: 30000000,
        requiresGroup: false,
      },
      {
        role: "reference_image",
        label: "Reference image",
        providerField: "reference_image_urls",
        inputKind: "image",
        minimum: 0,
        maximum: 9,
        acceptedMimeTypes: [
          "image/jpeg",
          "image/png",
          "image/webp",
          "image/bmp",
          "image/tiff",
          "image/gif",
        ],
        maxBytes: 30000000,
        requiresGroup: false,
      },
      {
        role: "reference_video",
        label: "Reference video",
        providerField: "reference_video_urls",
        inputKind: "video",
        minimum: 0,
        maximum: 3,
        acceptedMimeTypes: ["video/mp4", "video/quicktime"],
        maxBytes: 50000000,
        minDurationSeconds: 2,
        maxDurationSeconds: 15,
        totalDurationSeconds: 15,
        requiresGroup: false,
      },
      {
        role: "reference_audio",
        label: "Reference audio",
        providerField: "reference_audio_urls",
        inputKind: "audio",
        minimum: 0,
        maximum: 3,
        acceptedMimeTypes: ["audio/wav", "audio/mpeg"],
        maxBytes: 15000000,
        minDurationSeconds: 2,
        maxDurationSeconds: 15,
        totalDurationSeconds: 15,
        requiresGroup: false,
      },
    ],
    referenceExclusivity: [
      {
        groups: [
          ["first_frame", "last_frame"],
          ["reference_image", "reference_video", "reference_audio"],
        ],
        reason:
          "First/last-frame generation and multimodal reference generation are mutually exclusive for this model.",
      },
    ],
    combinedMediaQuota: undefined,
    incompatibilities: [],
    audioBehavior: {
      behavior: "generated-and-reference",
      notes:
        "Generated audio is optional; multimodal reference mode also accepts documented audio references.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl: "https://docs.kie.ai/market/bytedance/seedance-2",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "kling-3-video",
    version: 1,
    displayName: "Kling 3",
    modelMaker: "Kuaishou",
    mediaKind: "video",
    adapter: "kling3",
    providerModelId: "kling-3.0/video",
    supportedModes: ["single-shot", "multi-shot", "element-reference"],
    prompt: { minimum: 1 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "audio",
        label: "Sound",
        providerField: "sound",
        kind: "boolean",
        required: true,
        defaultValue: { value: false, source: "provider" },
        help: "Enable or disable generated sound effects. Multi-shot defaults to on.",
      },
      {
        key: "duration",
        label: "Duration",
        providerField: "duration",
        kind: "enum",
        values: [
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
        ],
        required: true,
        defaultValue: { value: "5", source: "provider" },
        help: "Total video duration from 3 through 15 seconds.",
      },
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: ["16:9", "9:16", "1:1"],
        required: true,
        defaultValue: { value: "16:9", source: "provider" },
        help: "May be omitted only when first/last-frame images determine the ratio.",
      },
      {
        key: "mode",
        label: "Quality mode",
        providerField: "mode",
        kind: "enum",
        values: ["std", "pro", "4K"],
        required: true,
        defaultValue: { value: "pro", source: "provider" },
        help: "Standard, professional, or 4K resolution mapping.",
      },
      {
        key: "multiShots",
        label: "Multi-shot",
        providerField: "multi_shots",
        kind: "boolean",
        required: true,
        defaultValue: { value: false, source: "provider" },
        help: "Use a sequence of up to five individually timed shots.",
      },
    ],
    references: [
      {
        role: "first_frame",
        label: "First frame",
        providerField: "image_urls",
        inputKind: "image",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: ["image/jpeg", "image/png"],
        requiresGroup: false,
      },
      {
        role: "last_frame",
        label: "Last frame",
        providerField: "image_urls",
        inputKind: "image",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: ["image/jpeg", "image/png"],
        requiresGroup: false,
      },
      {
        role: "element_image",
        label: "Element images",
        providerField: "element_input_urls",
        inputKind: "image",
        minimum: 2,
        maximum: 4,
        acceptedMimeTypes: ["image/jpeg", "image/png"],
        maxBytes: 10000000,
        requiresGroup: true,
      },
      {
        role: "element_video",
        label: "Element video",
        providerField: "element_input_urls",
        inputKind: "video",
        minimum: 1,
        maximum: 1,
        acceptedMimeTypes: ["video/mp4", "video/quicktime"],
        minDurationSeconds: 3,
        maxDurationSeconds: 30,
        requiresGroup: true,
      },
      {
        role: "element_audio",
        label: "Element audio",
        providerField: "element_input_audio_urls",
        inputKind: "audio",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: ["audio/mpeg", "audio/wav", "audio/mp4"],
        minDurationSeconds: 5,
        maxDurationSeconds: 30,
        requiresGroup: true,
      },
    ],
    referenceExclusivity: [
      {
        groups: [["element_image"], ["element_video"]],
        reason:
          "Each named element uses either 2–4 images or one video source, not both.",
      },
    ],
    incompatibilities: [],
    multiShot: {
      enabledField: "multi_shots",
      promptsField: "multi_prompt",
      maximumShots: 5,
      promptMaxLength: 500,
      shotDurationMinimum: 1,
      shotDurationMaximum: 12,
      totalMustMatchDuration: true,
    },
    audioBehavior: {
      behavior: "generated-and-reference",
      notes:
        "Sound effects are toggleable. Named elements may also include one 5–30 second audio reference.",
    },
    costWarning: {
      estimateAvailable: false,
      text: "Professional and 4K modes can use more credits. Exact usage remains estimated until completion.",
    },
    source: {
      documentationUrl: "https://docs.kie.ai/market/kling/kling-3-0",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "wan-2-7-text-video",
    version: 1,
    displayName: "Wan 2.7",
    modelMaker: "Alibaba",
    mediaKind: "video",
    adapter: "wan27",
    providerModelId: "wan/2-7-text-to-video",
    supportedModes: ["text-to-video", "audio-guided-text-to-video"],
    prompt: { minimum: 1, maximum: 5000 },
    negativePrompt: { supported: true, maximum: 500 },
    technical: [
      {
        key: "negativePrompt",
        label: "Negative prompt",
        providerField: "negative_prompt",
        kind: "string",
        maxLength: 500,
        required: false,
        help: "Optional exclusions, up to 500 characters.",
      },
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["720p", "1080p"],
        required: false,
        defaultValue: { value: "1080p", source: "provider" },
        help: "720p or 1080p.",
      },
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "ratio",
        kind: "enum",
        values: ["16:9", "9:16", "1:1", "4:3", "3:4"],
        required: false,
        defaultValue: { value: "16:9", source: "provider" },
        help: "Documented landscape, portrait, square, and 4:3 ratios.",
      },
      {
        key: "duration",
        label: "Duration",
        providerField: "duration",
        kind: "integer",
        minimum: 2,
        maximum: 15,
        step: 1,
        required: false,
        defaultValue: { value: 5, source: "provider" },
        help: "Whole seconds from 2 through 15.",
      },
      {
        key: "promptExtend",
        label: "Prompt extension",
        providerField: "prompt_extend",
        kind: "boolean",
        required: false,
        defaultValue: { value: true, source: "provider" },
        help: "Enable the documented intelligent prompt rewriting option.",
      },
      {
        key: "watermark",
        label: "Watermark",
        providerField: "watermark",
        kind: "boolean",
        required: false,
        defaultValue: { value: false, source: "provider" },
        help: "Add an AI-generated watermark.",
      },
      {
        key: "seed",
        label: "Seed",
        providerField: "seed",
        kind: "integer",
        minimum: 0,
        maximum: 2147483647,
        step: 1,
        required: false,
        help: "Optional reproducibility seed.",
      },
    ],
    references: [
      {
        role: "reference_audio",
        label: "Audio track",
        providerField: "audio_url",
        inputKind: "audio",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: ["audio/mpeg", "audio/wav", "audio/mp4"],
        requiresGroup: false,
      },
    ],
    referenceExclusivity: [],
    incompatibilities: [],
    audioBehavior: {
      behavior: "reference-only",
      notes:
        "The text-to-video contract accepts one optional custom audio URL; it does not expose generated-audio control.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl: "https://docs.kie.ai/market/wan/2-7-text-to-video",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "gemini-omni-video",
    version: 1,
    displayName: "Gemini Omni Video",
    modelMaker: "Google",
    mediaKind: "video",
    adapter: "geminiOmniVideo",
    providerModelId: "gemini-omni-video",
    supportedModes: ["text-to-video", "multimodal-reference-to-video"],
    prompt: { minimum: 1, maximum: 20000 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "duration",
        label: "Duration",
        providerField: "duration",
        kind: "enum",
        values: ["4", "6", "8", "10"],
        required: true,
        defaultValue: { value: "4", source: "application" },
        help: "4, 6, 8, or 10 seconds. Omitted when a source video determines output duration.",
      },
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: ["16:9", "9:16"],
        required: false,
        defaultValue: { value: "16:9", source: "application" },
        help: "Landscape or portrait.",
      },
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["720p", "1080p", "4k"],
        required: false,
        defaultValue: { value: "720p", source: "provider" },
        help: "720p, 1080p, or 4k.",
      },
      {
        key: "seed",
        label: "Seed",
        providerField: "seed",
        kind: "integer",
        minimum: 0,
        maximum: 2147483647,
        step: 1,
        required: false,
        help: "Optional reproducibility seed.",
      },
    ],
    references: [
      {
        role: "reference_image",
        label: "Reference image",
        providerField: "image_urls",
        inputKind: "image",
        minimum: 0,
        maximum: 7,
        acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
        maxBytes: 20000000,
        requiresGroup: false,
      },
      {
        role: "reference_audio",
        label: "Audio identity",
        providerField: "audio_ids",
        inputKind: "external_id",
        minimum: 0,
        maximum: 3,
        acceptedMimeTypes: [],
        requiresGroup: false,
      },
      {
        role: "reference_video",
        label: "Source video",
        providerField: "video_list",
        inputKind: "video",
        minimum: 0,
        maximum: 1,
        acceptedMimeTypes: ["video/mp4", "video/quicktime", "video/webm"],
        maxBytes: 100000000,
        maxDurationSeconds: 30,
        requiresGroup: false,
      },
      {
        role: "character",
        label: "Character identity",
        providerField: "character_ids",
        inputKind: "external_id",
        minimum: 0,
        maximum: 3,
        acceptedMimeTypes: [],
        requiresGroup: false,
      },
    ],
    referenceExclusivity: [],
    combinedMediaQuota: {
      limit: 7,
      weights: { reference_image: 1, reference_video: 2, character: 1 },
      reason:
        "Images use one unit, the single video uses two, and character IDs use one; their combined total cannot exceed seven.",
    },
    incompatibilities: [],
    audioBehavior: {
      behavior: "reference-only",
      notes:
        "Up to three IDs from the companion audio model may guide generation; generated-audio toggle is not documented.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl: "https://docs.kie.ai/market/gemini-omni-video",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "nano-banana-2",
    version: 1,
    displayName: "Nano Banana 2",
    modelMaker: "Google",
    mediaKind: "image",
    adapter: "nanoBanana2",
    providerModelId: "nano-banana-2",
    supportedModes: ["text-to-image", "reference-image-to-image"],
    prompt: { minimum: 1, maximum: 20000 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: [
          "1:1",
          "2:3",
          "3:2",
          "1:4",
          "4:1",
          "3:4",
          "4:3",
          "4:5",
          "5:4",
          "1:8",
          "8:1",
          "9:16",
          "16:9",
          "21:9",
          "auto",
        ],
        required: false,
        defaultValue: { value: "auto", source: "provider" },
        help: "All ratios documented for this image model.",
      },
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["1K", "2K", "4K"],
        required: false,
        defaultValue: { value: "1K", source: "provider" },
        help: "1K, 2K, or 4K.",
      },
      {
        key: "outputFormat",
        label: "Output format",
        providerField: "output_format",
        kind: "enum",
        values: ["png", "jpg"],
        required: false,
        defaultValue: { value: "jpg", source: "provider" },
        help: "PNG or JPEG output.",
      },
    ],
    references: [
      {
        role: "reference_image",
        label: "Reference image",
        providerField: "image_input",
        inputKind: "image",
        minimum: 0,
        maximum: 14,
        acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
        maxBytes: 30000000,
        requiresGroup: false,
      },
    ],
    referenceExclusivity: [],
    incompatibilities: [],
    audioBehavior: {
      behavior: "unsupported",
      notes: "This image contract has no audio input or output control.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl: "https://docs.kie.ai/market/google/nanobanana2",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "gpt-image-2",
    version: 1,
    displayName: "GPT Image 2",
    modelMaker: "OpenAI",
    mediaKind: "image",
    adapter: "gptImage2",
    providerModelId: "gpt-image-2-text-to-image",
    supportedModes: ["text-to-image"],
    prompt: { minimum: 1, maximum: 20000 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: [
          "auto",
          "1:1",
          "3:2",
          "2:3",
          "4:3",
          "3:4",
          "5:4",
          "4:5",
          "16:9",
          "9:16",
          "2:1",
          "1:2",
          "3:1",
          "1:3",
          "21:9",
          "9:21",
        ],
        required: false,
        defaultValue: { value: "auto", source: "provider" },
        help: "Documented text-to-image ratios.",
      },
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["1K", "2K", "4K"],
        required: false,
        defaultValue: { value: "1K", source: "application" },
        help: "1K, 2K, or 4K subject to aspect-ratio restrictions.",
      },
    ],
    references: [],
    referenceExclusivity: [],
    incompatibilities: [
      {
        when: { resolution: "2K" },
        disallow: { aspectRatio: ["5:4", "4:5", "3:1", "1:3", "9:21"] },
        reason: "These aspect ratios are not supported at 2K.",
      },
      {
        when: { resolution: "4K" },
        disallow: {
          aspectRatio: ["1:1", "5:4", "4:5", "3:1", "1:3", "9:21", "auto"],
        },
        reason:
          "The documented 4K contract excludes square, auto, and the listed extreme ratios.",
      },
      {
        when: { aspectRatio: "auto" },
        disallow: { resolution: ["2K", "4K"] },
        reason: "Auto aspect ratio is only supported at 1K.",
      },
    ],
    audioBehavior: {
      behavior: "unsupported",
      notes: "This image contract has no audio input or output control.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl:
        "https://docs.kie.ai/market/gpt/gpt-image-2-text-to-image",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "grok-imagine-image-2",
    version: 1,
    displayName: "Grok Imagine Image 2",
    modelMaker: "xAI",
    mediaKind: "image",
    adapter: "grokImage2",
    providerModelId: "grok-imagine-image-2-0/text-to-image",
    supportedModes: ["text-to-image"],
    prompt: { minimum: 1 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: ["1:1", "2:3", "3:2", "16:9", "9:16"],
        required: true,
        defaultValue: { value: "1:1", source: "application" },
        help: "The five documented output ratios.",
      },
    ],
    references: [],
    referenceExclusivity: [],
    incompatibilities: [],
    audioBehavior: {
      behavior: "unsupported",
      notes: "This image contract has no audio input or output control.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl:
        "https://docs.kie.ai/market/grok-imagine-image-2-0/text-to-image",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
  {
    contractVersion: "1.0.0",
    appModelKey: "grok-imagine-video",
    version: 1,
    displayName: "Grok Imagine Video",
    modelMaker: "xAI",
    mediaKind: "video",
    adapter: "grokVideo",
    providerModelId: "grok-imagine/text-to-video",
    supportedModes: ["text-to-video"],
    prompt: { minimum: 1, maximum: 5000 },
    negativePrompt: { supported: false },
    technical: [
      {
        key: "aspectRatio",
        label: "Aspect ratio",
        providerField: "aspect_ratio",
        kind: "enum",
        values: ["2:3", "3:2", "1:1", "16:9", "9:16"],
        required: false,
        defaultValue: { value: "2:3", source: "provider" },
        help: "Documented portrait, landscape, square, widescreen and vertical ratios.",
      },
      {
        key: "mode",
        label: "Motion mode",
        providerField: "mode",
        kind: "enum",
        values: ["fun", "normal", "spicy"],
        required: false,
        defaultValue: { value: "normal", source: "provider" },
        help: "Creative, balanced, or more intense motion.",
      },
      {
        key: "duration",
        label: "Duration",
        providerField: "duration",
        kind: "integer",
        minimum: 6,
        maximum: 30,
        step: 1,
        required: false,
        defaultValue: { value: 6, source: "application" },
        help: "Whole seconds from 6 through 30.",
      },
      {
        key: "resolution",
        label: "Resolution",
        providerField: "resolution",
        kind: "enum",
        values: ["480p", "720p", "1080p"],
        required: false,
        defaultValue: { value: "480p", source: "provider" },
        help: "480p, 720p, or 1080p.",
      },
    ],
    references: [],
    referenceExclusivity: [],
    incompatibilities: [],
    audioBehavior: {
      behavior: "unsupported",
      notes:
        "The text-to-video contract does not document sound generation or audio references.",
    },
    costWarning: noEstimate,
    source: {
      documentationUrl: "https://docs.kie.ai/market/grok-imagine/text-to-video",
      providerSchemaVersion: schemaVersion,
      verifiedAt,
    },
  },
] satisfies ModelCapability[];

export const MODEL_CAPABILITIES = capabilities.map((capability) =>
  modelCapabilitySchema.parse(capability),
);

export function getCapability(appModelKey: string) {
  return MODEL_CAPABILITIES.find(
    (capability) => capability.appModelKey === appModelKey,
  );
}

export function publicCapability(capability: ModelCapability) {
  const {
    providerModelId: _providerModelId,
    adapter: _adapter,
    ...publicFields
  } = capability;
  void _providerModelId;
  void _adapter;
  return publicFields;
}

export function validateCustomCapability(input: unknown) {
  return modelCapabilitySchema.parse(input);
}
