import { modelCapabilitySchema } from "@/lib/generation/capability";

export const LTX_25_CAPABILITY_V4 = modelCapabilitySchema.parse({
  contractVersion: "1.0.0",
  appModelKey: "ltx-2-5",
  version: 4,
  displayName: "LTX-2.5",
  modelMaker: "Lightricks",
  mediaKind: "video",
  adapter: "ltx25",
  providerModelId: "self-hosted/ltx-2.5-distilled",
  supportedModes: [
    "text-to-video",
    "first-frame-to-video",
    "prompt-image-anchors-to-video",
  ],
  prompt: { minimum: 3, maximum: 20_000 },
  negativePrompt: { supported: false },
  technical: [
    {
      key: "resolution",
      label: "Resolution",
      providerField: "resolution",
      kind: "enum",
      values: ["720p", "1080p"],
      required: true,
      defaultValue: { value: "720p", source: "application" },
      help: "VesperFrame maps this to dimensions divisible by 64 for the official LTX-2.5 distilled pipeline.",
    },
    {
      key: "aspectRatio",
      label: "Aspect ratio",
      providerField: "aspect_ratio",
      kind: "enum",
      values: ["16:9", "9:16", "1:1"],
      required: true,
      defaultValue: { value: "16:9", source: "application" },
      help: "Landscape, portrait, or square dimensions validated by the private worker.",
    },
    {
      key: "duration",
      label: "Duration",
      providerField: "duration",
      kind: "enum",
      values: ["auto", "5", "10", "12"],
      required: true,
      defaultValue: { value: "auto", source: "application" },
      help: "Auto uses the duration head up to 12 seconds. Twelve seconds is the longest fixed profile enabled on this worker.",
    },
    {
      key: "frameRate",
      label: "Frame rate",
      providerField: "frame_rate",
      kind: "enum",
      values: [24],
      required: true,
      defaultValue: { value: 24, source: "application" },
      help: "The deployed distilled profile is fixed at 24 fps.",
    },
    {
      key: "promptExtend",
      label: "Prompt enhancement",
      providerField: "enhance_prompt",
      kind: "boolean",
      required: true,
      defaultValue: { value: false, source: "application" },
      help: "Use the official optional prompt-enhancement stage.",
    },
    {
      key: "seed",
      label: "Seed",
      providerField: "seed",
      kind: "integer",
      minimum: 0,
      maximum: 2_147_483_647,
      step: 1,
      required: false,
      help: "Optional deterministic seed.",
    },
  ],
  references: [
    {
      role: "first_frame",
      label: "Opening image (@image / @image1)",
      providerField: "images",
      inputKind: "image",
      minimum: 0,
      maximum: 1,
      acceptedMimeTypes: ["image/jpeg", "image/png"],
      maxBytes: 20_000_000,
      requiresGroup: false,
    },
    {
      role: "reference_image",
      label: "Prompt image (@image1 … @image9)",
      providerField: "images",
      inputKind: "image",
      minimum: 0,
      maximum: 9,
      acceptedMimeTypes: ["image/jpeg", "image/png"],
      maxBytes: 20_000_000,
      requiresGroup: false,
    },
  ],
  referenceExclusivity: [],
  combinedMediaQuota: {
    limit: 9,
    weights: { first_frame: 1, reference_image: 1 },
    reason: "LTX-2.5 accepts at most nine visual anchors in one generation.",
  },
  incompatibilities: [],
  audioBehavior: {
    behavior: "always-generated",
    notes:
      "The official distilled pipeline jointly generates synchronized video and audio; no decorative audio toggle is shown.",
  },
  costWarning: {
    estimateAvailable: false,
    text: "This release uses the official distilled pipeline. Self-hosted compute cost depends on RunPod GPU time and cold starts; usage remains estimated until the worker reports runtime metadata.",
  },
  source: {
    documentationUrl: "https://huggingface.co/Lightricks/LTX-2.5",
    providerSchemaVersion: "ltx-pipelines-a95ab856-multi-image",
    verifiedAt: "2026-09-01",
  },
});
